# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_jummah_avail', models.BooleanField(default=True)),
                ('is_wuzu_avail', models.BooleanField(default=True)),
                ('is_women_facility', models.BooleanField(default=False)),
                ('is_parking_avail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HasBeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musallah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musallah_name', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=100)),
                ('contact_no', models.BigIntegerField()),
                ('maslak', models.CharField(max_length=20)),
                ('is_musallah', models.BooleanField(default=False)),
                ('distance_near_stn', models.DecimalField(decimal_places=4, max_digits=4)),
                ('musallah_lat', models.DecimalField(decimal_places=4, max_digits=4)),
                ('musallah_lng', models.DecimalField(decimal_places=4, max_digits=4)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NamazTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaz_fajr', models.DateTimeField()),
                ('namaz_zuhr', models.DateTimeField()),
                ('namaz_asr', models.DateTimeField()),
                ('namaz_magrib', models.DateTimeField()),
                ('namaz_isha', models.DateTimeField()),
                ('namaz_jummah', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RamzanTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taravih_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('eid_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('is_iftar_avail', models.BooleanField(default=True)),
                ('musullah_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musallahapp.Musallah')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_loc_lat', models.FloatField()),
                ('user_loc_lng', models.FloatField()),
                ('user_contact', models.BigIntegerField()),
                ('user_area', models.CharField(max_length=200)),
                ('user_pincode', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='hasbeen',
            name='musallah_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musallahapp.Musallah'),
        ),
        migrations.AddField(
            model_name='hasbeen',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musallahapp.Users'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='musullah_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musallahapp.Musallah'),
        ),
    ]
