# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musallahapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musallah',
            name='distance_near_stn',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='musallah',
            name='musallah_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='musallah',
            name='musallah_lng',
            field=models.FloatField(),
        ),
    ]
